# conf/vector_hiss2_config.yaml
defaults:
  - config
  - override model: hierarchical_mamba2
  - override data_env: VectorEnv
  - _self_


model:
  model_dim: 64
  dropout:   0.1

  hl_model:
    d_intermediate: 128
  #  _target_: hiss.models.MambaNet
  #  model_dim: ${model_dim}
  #  nlayers:   4
  #  ssm_cfg:
  #    layer: Mamba2
  #  norm_epsilon: 1e-5
  #  rms_norm:     false
  #  fused_add_norm: false
  #  residual_in_fp32: false

  ll_model:
    _target_:       mamba_ssm.modules.mamba2.Mamba2
    model_dim:        32
    d_intermediate: 128
    n_layers:        4
    ssm_cfg:
    layer: Mamba2
    norm_epsilon:   1e-5
    rms_norm:       false
    fused_add_norm: false
    residual_in_fp32: false
