defaults:
- config
- override model: hierarchical_mamba2
- override data_env: VectorEnv
- override model/hl_model@model.model.hl_model: mamba2
- _self_

model:
  model:
    model_dim: 64
    dropout: 0.1
    hl_model:
      nlayers: 4
    ll_model:
      model_dim: 32
      nlayers: 4
