# conf/vector_hiss2_config.yaml
defaults:
  - config
  - override model: hierarchical_mamba2
  - override data_env: VectorEnv
  - override model/hl_model@model.model.hl_model: mamba2
  - _self_

low_freq_factor: 10


model:
  type:      hierarchical_mamba2
  _partial_: true

  model_dim: 64
  dropout:   0.1
  freq_ratio: 10

  hl_model:
    _target_: hiss.models.MambaNet
    model_dim: 64
    nlayers:   4

    d_model:        32
    d_intermediate: 128
    ssm_cfg:
      layer: Mamba2
    norm_epsilon:   1e-5
    rms_norm:       false
    fused_add_norm: false
    residual_in_fp32: false

  ll_model:
    _target_: mamba_ssm.modules.mamba2.Mamba2
    model_dim:  32
    d_intermediate: 128
    nlayers:   4
    ssm_cfg:
      layer: Mamba2
    norm_epsilon:   1e-5
    rms_norm:       false
    fused_add_norm: false
    residual_in_fp32: false
