type: mamba2
model:
  _target_: mamba_ssm.modules.mamba2.Mamba2
  _partial_: true
  model_dim: 32
  d_intermediate: 128
  n_layers: 4
  ssm_cfg: { "layer": "Mamba2" }
  norm_epsilon: 1e-5
  rms_norm: false
  fused_add_norm: false
  residual_in_fp32: false
