type: mamba
model:
  _target_: hiss.models.MambaModel
  _partial_: true
  model_dim: 32
  d_intermediate: 128
  n_layers: 4
  ssm_cfg: { "layer": "Mamba2" }
  norm_epsilon: 1e-5
  rms_norm: false
  fused_add_norm: false
  residual_in_fp32: false
